# Generated by Django 5.2.12 on 2026-04-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='livres', to='api.tag'),
        ),
    ]
